# Book Summarizer Configuration Constants

# Summary Length (Words)
SUMMARY_MAX_WORDS = 150
SUMMARY_MIN_WORDS = 100

# Analytical Framework
TERMINOLOGY_MIN_COUNT = 5
TERMINOLOGY_MAX_COUNT = 7

# Logical Chain Steps
LOGICAL_CHAIN_MIN_STEPS = 4
LOGICAL_CHAIN_MAX_STEPS = 6

# Truncation Limits (Characters)
DRAFT_TRUNCATION_FULL = 4000
DRAFT_TRUNCATION_PARTIAL = 1000
CRITIC_DRAFT_CHAR_LIMIT = 8000
CONTEXT_PREVIEW_CHARS = 500

# Token Estimation
MAX_PROMPT_TOKENS = 180000
AVG_CHARS_PER_TOKEN = 4
